on:
  push:
    tags:
      - 'v*'
name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Tag Info
        run: |
          echo "subject" && git tag -l "${GITHUB_REF##*/}" --format='%(subject)'
          echo "body" &&git tag -l "${GITHUB_REF##*/}" --format='%(body)'