on:
  push:
    tags:
      - 'v*'
name: release-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Tag Info
        run: |
          git tag -l "${GITHUB_REF##*/}" --format='%(subject)'
          git tag -l "${GITHUB_REF##*/}" --format='%(body)'