on:
  workflow_dispatch:

name: Publish route list on Test env
jobs:
  route:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo ${{ secrets.TELEGRAM_TO }}
      - run: echo ${{ secrets.TELEGRAM_TOKEN }}
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step.
